### ISSUE TITLE
cpu inference

### ISSUE THREAD

**Issue by AK391** [ashkamath/mdetr#3]
is it possible to do inference on cpu?

**Comment by ashkamath** [comment]
yup, just pass --device=cpu

**Comment by AK391** [comment]
@ashkamath thanks I am getting Your session crashed after using all available RAM in colab

**Comment by AK391** [comment]
@ashkamath could be related to pass PIL.Image.Image instead of  <class 'PIL.JpegImagePlugin.JpegImageFile'>

**Comment by alcinos** [comment]
Hi @AK391 
Did you try requesting an instance with more ram? I just tried doing inference on CPU in the colab and it worked fine.

Best of luck

**Comment by AK391** [comment]
@alcinos yes that should work but wondering why this happens for some images and not others

**Comment by alcinos** [comment]
Interesting, do you have an image where it consistently fails, starting from a fresh instance? (Note that in colab, there might be a lot of variables that stay in memory, progressively clogging it over time)

One thing that comes to mind is that your input image is too big. The line you are referring to is doing the pre-processing, namely resize such that the small size is 800 and the long size it at most 1333, followed by conversion to torch tensor and normalization. None of these operations should be particularly RAM heavy, unless the input image is huge or somehow malformed.

If that makes things easier, you could try to reduce a bit the inference size in the transform, like 600 instead of 800. This will incur a slight decrease in performance, especially for small objects, but should still otherwise work fine.

**Comment by AK391** [comment]
@alcinos I tried the same image from the notebook but download it first
![download (10)](https://user-images.githubusercontent.com/81195143/116936545-01013580-ac36-11eb-8a05-e2d0978e424f.png)

**Comment by AK391** [comment]
@alcinos session still crashes at 600
