### ISSUE TITLE
Question about bounding box format

### ISSUE THREAD

**Issue by Dou-Yiming** [ashkamath/mdetr#72]
Thanks for the amazing work! However, I got a little confused when going through the code.

In function _loss_boxes_, you said that the target boxes are expected in format (center_x, center_y, h, w), but in function _ConvertCocoPolysToMask_ the following computation is done on the boxes:
`boxes[:, 2:] += boxes[:, :2]
 boxes[:, 0::2].clamp_(min=0, max=w)
 boxes[:, 1::2].clamp_(min=0, max=h)`

This means that target['boxes'] is in format (x1, y1, x2, y2), which is contradicts with (center_x, center_y, h, w).

May I ask in which function are target['boxes'] converted to format (center_x, center_y, h, w) or whether I have missed something?

Thanks a lot!!

**Comment by alcinos** [comment]
Hi @Dou-Yiming 

The targets are converted to CxCyWH at the end of the preprocessing transformations, namely here: https://github.com/ashkamath/mdetr/blob/bf09d98b0b41cd615185dcb0082299a5ba24c319/datasets/transforms.py#L267

We first convert to XYXY (as you noted) because the math for the preprocessing (eg cropping) is easier, but then go back to CxCyWH. Sorry for the confusion.

Hope this helps

**Comment by Dou-Yiming** [comment]
> Hi @Dou-Yiming
> 
> The targets are converted to CxCyWH at the end of the preprocessing transformations, namely here:
> 
> https://github.com/ashkamath/mdetr/blob/bf09d98b0b41cd615185dcb0082299a5ba24c319/datasets/transforms.py#L267
> 
> We first convert to XYXY (as you noted) because the math for the preprocessing (eg cropping) is easier, but then go back to CxCyWH. Sorry for the confusion.
> 
> Hope this helps

Thanks for the rapid reply, the question is solved!
